---
- hosts: localhost
  pre_tasks:
    - name: install boto 3
      pip:
        name: boto3
    - name: get instance metadata
      ec2_metadata_facts:
    - name: get instance facts
      ec2_instance_facts:
        instance_ids:
          - "{{ ansible_ec2_instance_id }}"
      register: instances
    - set_fact:
        instance_role: "{{ instances.instances[0].tags.role }}"
  roles:
    - common

  post_tasks:
    - debug:
        var: instance_role
    - name: run jumphost role
      include_role:
        name: jumphost
      when: instance_role == 'jumphost'

- imclude_playbook: setup-cluster.yml
  when: instance_role == 'jumphost'
