---
# tasks for setting up jenkins
# yamllint disable rule:truthy

- name: generate a kubernetes cert
  include_tasks: kubernetes.yml

- name: slurp pfx from master
  fetch:
    src: /etc/kubernetes/pki/jenkins.pfx
    dest: /tmp/jenkins.pfx
    flat: yes
  delegate_to: "{{ groups['k8smaster'][0] }}"
  register: jenkins_cert

- name:
  fetch:
    src: /etc/kubernetes/pki/ca.crt
    dest: /tmp/kubernetes-ca.crt
    flat: yes
  delegate_to: "{{ groups['k8smaster'][0] }}"

- name: write out pfx on jenkins server
  copy:
    dest: /var/lib/jenkins/kubernetes.pfx
    src: /tmp/jenkins.pfx
    remote_src: no
    owner: jenkins
    group: jenkins

- name: write ca cert on jenkins
  copy:
    dest: /var/lib/jenkins/kubernetes-ca.crt
    src: /tmp/kubernetes-ca.crt
    owner: jenkins
    group: jenkins

- name: get token from s3
  aws_s3:
    mode: get
    bucket: "{{ keystore }}"
    object: jenkins_github_token
    dest: /tmp/jenkins_github_token
  changed_when: false

- name: slurp into variable
  slurp:
    src: /tmp/jenkins_github_token
  register: jenkins_github_token

- name: add jenkins sysconfig settings
  lineinfile:
    path: /etc/sysconfig/jenkins
    line: "{{ item.name}}={{ item.value }}"
    regexp: "^{{ item.name }}.*"
  with_items:
    # yamllint disable rule:line-length
    - {name: JENKINS_ADDRESS, value: "http://{{ ansible_default_ipv4.address }}:8080"}
    - {name: JENKINS_GITHUB_TOKEN, value: "{{ jenkins_github_token.content | b64decode }}"}
    - {name: JENKINS_JAVA_OPTS, value: "-Djenkins.install.runSetupWizard=false"}
    - {name: KUBERNETES_MASTER, value: "https://{{ hostvars[groups['k8smaster'][0]].ansible_default_ipv4.address}}:6443"}
    - {name: JENKINS_LISTEN_ADDRESS, value: "0.0.0.0"}
    # yamllint enable rule:line-length
  notify: restart jenkins

- name: remove the file
  file:
    path: /tmp/jenkins_github_token
    state: absent
  changed_when: false

- name: copy jenkins unit file
  copy:
    src: jenkins.service
    dest: /etc/systemd/system/jenkins.service
    owner: root
    group: root
    mode: 0644
  register: reload_jenkins

- name: reload systemd
  command: systemctl daemon-reload
  when: reload_jenkins.changed

- name: create kubeconfig dir
  file:
    path: /var/lib/jenkins/.kube
    owner: jenkins
    group: jenkins
    state: directory

- name: write kubeconfig on jenkins
  copy:
    dest: /var/lib/jenkins/.kube/config
    content: '{{ kubeconfig_content.content | b64decode }}'
    owner: jenkins
    group: jenkins
    mode: 0600

- name: install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.9.1/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 0755
    owner: root
    group: root

# Init.groovy.d
- name: copy init.groovy.d scripts
  copy:
    src: init.groovy.d/
    dest: /var/lib/jenkins/init.groovy.d
    owner: jenkins
    group: jenkins
  notify: restart jenkins

- name: enable & start jenkins
  systemd:
    state: started
    enabled: yes
    name: jenkins
