# expects
# kubeconfig = path
# k8s_masterIp = hostvars[groups['k8smaster'][0]].ansible_eth1.ipv4.address
# k8s_masterPort = 6443
# user
- name: generate kubeconfig
  block:
    - name: create kubeconfig entry
      command: >
        kubectl config set-cluster default
          --server=https://{{ k8s_masterIp }}:{{ k8s_masterPort }}
          --certificate-authority=/etc/kubernetes/pki/ca.crt
          --embed-certs=true
          --kubeconfig={{ kubeconfig }}

    - name: create user entry
      command: >
        kubectl  config set-credentials {{ user }}
          --username={{ user }}
          --client-certificate=/etc/kubernetes/pki/{{ user }}.cert
          --client-key=/etc/kubernetes/pki/{{ user }}.key
          --embed-certs=true
          --kubeconfig={{ kubeconfig }}

    - name: create context entry
      command: >
        kubectl config set-context default
          --cluster=default
          --user={{ user }}
          --kubeconfig={{ kubeconfig }}

    - name: set current context
      command: >
        kubectl config use-context default
          --kubeconfig={{ kubeconfig }}
    - name: slurp kubeconfig
      slurp:
        src: "{{ kubeconfig }}"
      register: kubeconfig_content
  delegate_to: "{{ groups['masters'][0] }}"
