---
# tasks file for jenkins
- name: create yum repo
  yum_repository:
    name: jenkins
    state: present
    gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
    gpgcheck: yes
    enabled: yes
    description: jenkins
    baseurl: https://pkg.jenkins.io/redhat/

- name: install packages
  yum:
    state: installed
    name:
      - java-1.8.0-openjdk
      - jenkins
      - git
      - make

- include_tasks: kubernetes.yml

- name: slurp pfx from master
  fetch:
    src: /etc/kubernetes/pki/jenkins.pfx
    dest: /tmp/jenkins.pfx
    flat: yes
  delegate_to: "{{ groups['masters'][0] }}"
  register: jenkins_cert

- name:
  fetch:
    src: /etc/kubernetes/pki/ca.crt
    dest: /tmp/kubernetes-ca.crt
    flat: yes
  delegate_to: "{{ groups['masters'][0] }}"

- name: write out pfx on jenkins server
  copy:
    dest: /var/lib/jenkins/kubernetes.pfx
    src: /tmp/jenkins.pfx
    remote_src: no
    owner: jenkins
    group: jenkins

- name: write ca cert on jenkins
  copy:
    dest: /var/lib/jenkins/kubernetes-ca.crt
    src: /tmp/kubernetes-ca.crt
    owner: jenkins
    group: jenkins

# Init.groovy.d
- name: copy init.groovy.d scripts
  copy:
    src: init.groovy.d/
    dest: /var/lib/jenkins/init.groovy.d
    owner: jenkins
    group: jenkins
  notify: restart jenkins

- name: enable & start jenkins
  systemd:
    state: started
    enabled: yes
    name: jenkins
