---
# tasks file for jumphost
# yamllint disable rule:truthy


- name: Get centos private key from s3 for {{ instance_user }}
  aws_s3:
    bucket: "{{ keystore }}"
    object: "{{ private_keyfile }}"
    dest: "{{ instance_user_home }}/.ssh/id_rsa"
    mode: get

- name: Set permissions on private key for {{ instance_user }}
  file:
    path: "{{ instance_user_home }}/.ssh/id_rsa"
    owner: "{{ instance_user }}"
    mode: 0600
    group: "{{ instance_user }}"

- name: Get centos private key from s3 for {{ root_user }}
  aws_s3:
    bucket: "{{ keystore }}"
    object: "{{ private_keyfile }}"
    dest: "{{ root_user_home }}/.ssh/id_rsa"
    mode: get

- name: Set permissions on private key for {{ root_user }}
  file:
    path: "{{ root_user_home }}/.ssh/id_rsa"
    owner: "{{ root_user }}"
    mode: 0600
    group: "{{ root_user }}"

- name: get instance facts
  ec2_instance_facts:
    filters:
      instance-state-name: running
  register: instances

- name: list inventory
  debug:
    msg: "Host: {{ item.private_ip_address }} Role: {{ item.tags.role }}"
  with_items: "{{ instances.instances }}"

- name: update inventory
  add_host:
    name: "{{ item.private_ip_address }}"
    groups: "{{ item.tags.role }}, all"
  with_items: "{{ instances.instances }}"


# tasks file for jenkins
- name: create yum repo
  yum_repository:
    name: jenkins
    state: present
    gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
    gpgcheck: yes
    enabled: yes
    description: jenkins
    baseurl: https://pkg.jenkins.io/redhat/

- name: install packages
  yum:
    state: installed
    name:
      - java-1.8.0-openjdk
      - jenkins
      - git
      - make



